"""Validation constants for the driver's license exam registration system."""

# Valid license types
VALID_LICENSE_TYPES = [
    "A",
    "A1",
    "A2",
    "B",
    "B96",
    "BE",
    "Bus",
    "Goods",
    "C",
    "C1",
    "C1E",
    "CE",
    "D",
    "D1",
    "D1E",
    "DE",
    "Bus",
    "Lorry",
    "Train driver",
    "Taxi",
    "AM",
    "Tractor",
    "ADR",
    "APV",
    "VVH",
]

# Valid test types
VALID_TEST_TYPES = ["practical driving test", "theory test"]

# Valid transmission types
VALID_TRANSMISSION_TYPES = ["manual", "automatic"]

# Valid locations
VALID_LOCATIONS = [
    "Alingsås",
    "Älmhult",
    "Ånge",
    "Ängelholm",
    "Arjeplog",
    "Arvidsjaur",
    "Arvika",
    "Avesta",
    "Boden",
    "Bollnäs",
    "Borås",
    "Borlänge",
    "Eksjö",
    "Enköping",
    "Eskilstuna",
    "Eslöv",
    "Fagersta",
    "Falkenberg",
    "Falköping",
    "Falun",
    "Farsta",
    "Finspång",
    "Flen",
    "Gällivare",
    "Gävle",
    "Gislaved",
    "Göteborg Högsbo",
    "Göteborg-Hisingen",
    "Halmstad",
    "Hammarstrand",
    "Haparanda",
    "Härnösand",
    "Hässleholm",
    "Hedemora",
    "Helsingborg",
    "HK",
    "Hudiksvall",
    "Järfälla",
    "Järpen",
    "Jokkmokk",
    "Jönköping",
    "Kalix",
    "Kalmar",
    "Karlshamn (NY)",
    "Karlskoga",
    "Karlskrona",
    "Karlstad",
    "Katrineholm",
    "Kinna",
    "Kiruna",
    "Kisa",
    "Köping",
    "Kramfors",
    "Kristianstad",
    "Kristinehamn",
    "Kumla",
    "Kungälv",
    "Kungsbacka",
    "Landskrona",
    "Lidköping",
    "Lindesberg",
    "Linköping",
    "Ljungby",
    "Ljusdal",
    "Ludvika",
    "Luleå",
    "Lund",
    "Lycksele",
    "Lysekil",
    "Malmö",
    "Malung",
    "Mariestad",
    "Mjölby",
    "Mora",
    "Motala",
    "Nässjö",
    "Norrköping",
    "Norrtälje 2",
    "Nybro",
    "Nyköping",
    "Nynäshamn",
    "Örebro",
    "Örnsköldsvik",
    "Oskarshamn",
    "Östersund",
    "Östhammar",
    "Övertorneå",
    "Pajala",
    "Piteå",
    "Ronneby",
    "Säffle",
    "Sala",
    "Sandviken",
    "Simrishamn",
    "Skellefteå",
    "Skövde",
    "Söderhamn",
    "Södertälje",
    "Sollefteå",
    "Sölvesborg",
    "Strömstad",
    "Strömsund",
    "Sundsvall",
    "Sunne",
    "Sveg",
    "Tranås",
    "Trelleborg",
    "Uddevalla",
    "Ulricehamn",
    "Umeå",
    "Upplands Väsby",
    "Uppsala",
    "Vänersborg",
    "Varberg",
    "Värnamo",
    "Västerås",
    "Västerhaninge",
    "Västervik",
    "Växjö",
    "Vetlanda",
    "Vilhelmina",
    "Vimmerby",
    "Visby",
    "Ystad",
] 