[project]
name = "trafikverket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ag2>=0.8.4",
    "browser-use>=0.1.40",
    "flask>=3.1.0",
    "nest-asyncio>=1.6.0",
    "streamlit>=1.44.0",
]
